apiVersion: autoscaling/v1
kind: VerticalPodAutoscaler
metadata:
  name: pressure-api-vpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pressure-api-deployment
  updatePolicy:
    updateMode: Recreate
  resourcePolicy:
    containerPolicies:
      - containerName: pressure-api
        controlledResources:
          - resource:
              - cpu
              - memory
            minimum:
              cpu: 100m
              memory: 50Mi
            maximum:
              cpu: 1
              memory: 500Mi
